layout_spectrum: 0.4328034666447098
typography_spectrum: 0.1683210204940031
color:
  brandColors:
    - '#FFFFFF'
    - '#4285F4'
    - '#000000'
    - '#EA4335'
    - '#FBBC05'
  brandStrength: 0.6038534167204236
  lightness: 0.26422107655149285
  saturation: 0.5376968115270322
  rhythmicContrast: 0.19134338769545356
name: digital agency
cta: {}
analytics:
  google: UA-59862159-4
opengraph: {}
purpose:
  - type: contact
    label: Email
    url: 'mailto:adrian@digitalagency.org.au'
  - type: contact
    label: Call
    url: 'tel:0407081084'
title: Digital Agency
description: Digital Marketing and Measurement for Nonprofits and SMBs
author:
  name: Adrian Wedd
  url: 'http://adrianwedd.com'
  email: adrian@digitalagency.org.au
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f89ccbca-d3bc-4acc-898c-fde6b839ff98.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f89ccbca-d3bc-4acc-898c-fde6b839ff98.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ffd9922a-b886-49e0-8c9d-0988c14d9f39.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ffd9922a-b886-49e0-8c9d-0988c14d9f39.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'http://d1g1tal.agency'
github: true
