name: digital agency
favicon: null
layout_spectrum: 0.941303
typography_spectrum: 0.80805
title: 'digital agency | designed by artificial intelligence.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4285f4'
    - '#000000'
    - '#ea4335'
    - '#fbbc05'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
