layout_spectrum: 0.43258366103136525
typography_spectrum: 0.8873333224673562
color:
  brandColors:
    - '#FFFFFF'
    - '#4285F4'
    - '#000000'
    - '#EA4335'
    - '#FBBC05'
  brandStrength: 0.606512737457207
  lightness: 0.2619539110800528
  saturation: 0.5336989770078165
  rhythmicContrast: 0.11949611180083881
name: digital agency
cta: {}
analytics:
  google: UA-59862159-4
opengraph: {}
purpose:
  - type: contact
    label: Email
    url: 'mailto:adrian@digitalagency.org.au'
  - type: contact
    label: Call
    url: 'tel:0407081084'
title: Digital Agency
description: Digital Marketing and Measurement for Nonprofits and SMBs
author:
  name: Adrian Wedd
  url: 'http://adrianwedd.com'
  email: adrian@digitalagency.org.au
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a4a96b5f-1e06-4ab8-badc-79f8b5aa436f.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a4a96b5f-1e06-4ab8-badc-79f8b5aa436f.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/766ad1e2-6fee-442c-951f-ef42a4f72b5a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/766ad1e2-6fee-442c-951f-ef42a4f72b5a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'http://d1g1tal.agency'
github: true
